# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Filtros e np.where()

A função `np.where()` é muito útil para fazer uma seleção condicional de elementos de um array. Por exemplo, em uma empresa, você pode querer identificar quais funcionários têm salários acima da média.


In [2]:
import numpy as np

# Salários dos funcionários
salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

# Calcular a média salarial
media_salarial = np.mean(salarios)

print(f"{media_salarial:.2f}")

3714.29


In [34]:
# Identificar funcionários com salários acima da média
funcionarios_acima_media = np.where(salarios > media_salarial)
print(salarios[funcionarios_acima_media])

print(salarios[salarios > media_salarial])
print(*np.where(salarios == np.max(salarios)))

[4000 4500 4000 5000]
[4000 4500 4000 5000]
[6]


In [41]:
# dar bônus de 10% para os funcionários com salários abaixo da média
print(salarios)
bonificacao = 0.1
print(np.where(salarios < media_salarial, salarios * (1 + bonificacao), salarios))

[3000 3500 4000 2000 4500 4000 5000]
[3300. 3850. 4000. 2200. 4500. 4000. 5000.]


In [46]:
# filtrar os salários entre 3000 e 4500 com where
filtro = np.where((salarios >= 3000) & (salarios <= 4500))
print(filtro)
print(salarios[filtro])

(array([0, 1, 2, 4, 5], dtype=int64),)
[3000 3500 4000 4500 4000]


In [49]:
# filtrar os salários abaixo de 3000 ou acima de 4500 com where
filtro = np.where((salarios < 3000) | (salarios > 4500))
print(filtro)
print(salarios[filtro])

(array([3, 6], dtype=int64),)
[2000 5000]
