## Exercício

Você é um engenheiro de produção e tem os tempos de ciclo (em minutos) de uma linha de produção em um array NumPy. Seu trabalho é identificar quaisquer tempos de ciclo que estão dois desvios padrão acima ou abaixo da média. Use o seguinte array para sua análise: `tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])`. 

In [12]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo) 
print(f"{media = }")
desvio_padrao = np.std(tempos_ciclo)
print(f"{desvio_padrao = }")

media = 5.8
desvio_padrao = 0.592546294487706


In [14]:
condicao = (tempos_ciclo > media + 2 * desvio_padrao) | (tempos_ciclo < media - 2 * desvio_padrao)
anomalias = tempos_ciclo[np.where(condicao)]
print(f"{anomalias = }")

anomalias = array([7.2])


In [15]:
print(condicao)

[False False False False False False False  True False]


In [17]:
condicao_contraria = (tempos_ciclo >= media - 2 * desvio_padrao) & (tempos_ciclo <= media + 2 * desvio_padrao)
print(tempos_ciclo[condicao_contraria])

[5.5 5.7 5.9 6.  5.8 5.6 5.7 4.8]


In [18]:
print(np.where(~condicao)) # Inversão da condição

(array([0, 1, 2, 3, 4, 5, 6, 8], dtype=int64),)


In [26]:
rng = np.random.default_rng(seed=0)
tempos_gerados = rng.normal(loc=media, scale=desvio_padrao, size=100)
print(tempos_gerados)

[5.87450098 5.72172175 6.17948007 5.86215818 5.4825911  6.01426181
 6.57268039 6.36118932 5.38300429 5.0501792  5.43068103 5.82448756
 4.42231163 5.67035581 5.06174008 5.36609769 5.47750136 5.61257751
 6.04391015 6.41773743 5.72383726 6.60969287 5.40584136 6.00828599
 6.33534791 5.85570664 5.35944227 5.25383504 5.52877626 5.9304758
 5.20175449 5.67605379 5.70565181 6.12047605 5.92719547 6.01057478
 5.41257628 5.72319792 6.26454176 6.68492709 5.05394538 6.69706992
 6.5974935  6.26296318 5.9567022  5.6139862  6.66394475 6.9615438
 6.86755207 6.57925986 6.01176444 5.08401527 5.79736072 6.18899179
 5.03658619 6.03412811 6.05471414 6.21243754 5.09835529 5.40791059
 5.54139191 5.10683821 6.83065599 5.50614994 5.99492973 5.6467838
 6.73828099 6.58237501 6.17529075 4.49431839 5.83082958 6.20511572
 6.39489371 5.43386147 6.87962608 5.01758352 5.40801402 6.35406041
 5.82906713 6.98651031 5.91170635 5.42480319 5.57627614 5.15344541
 5.04291535 6.17354799 6.14436765 6.56708603 5.35286113 6.8008743

In [27]:
print(media)
print(tempos_gerados.mean())

5.8
5.848053545223129


In [28]:
print(desvio_padrao)
print(tempos_gerados.std())

0.592546294487706
0.5701068395534514


In [29]:
condicao = (tempos_gerados > tempos_gerados.mean() + 2 * tempos_gerados.std()) | (tempos_gerados < tempos_gerados.mean() - 2 * tempos_gerados.std())
print(np.where(condicao))
print(tempos_gerados[condicao])

(array([12, 69], dtype=int64),)
[4.42231163 4.49431839]
